### ISSUE TITLE
Unclear what the driven version of the axis refers to in the BOM

### ISSUE THREAD

**Issue by polygonhell** [eclsnowman/Eustathios-Spider-V2#10]

**Comment by eclsnowman** [comment]
This should help make it clear:
Green = Driven
Purple = Idle

![screen shot 06-12-17 at 04 17 pm](https://user-images.githubusercontent.com/2068891/27055636-ab511012-4f8a-11e7-80ac-f161f7f27ef3.PNG)

**Comment by polygonhell** [comment]
Thanks Eric,
That makes things clear, for some reason when I read the BOM, I read it as an alternative configuration.
